language: node_js
sudo: false
node_js:
  - "10"
install:
  - npm install
before_script:
  - npm install -g gulp-cli
script:
  - gulp prod-test
after_success: 
- 'nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'